name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: self-hosted
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          runAsHostUser: true
          allowDirtyBuild: true
          unityVersion: auto
          versioning: Semantic
          androidExportType: androidPackage
          androidSymbolType: none
          dockerIsolationMode: default
          containerRegistryRepository: unityci/editor
          containerRegistryImageVersion: 3
          awsStackName: game-ci
          providerStrategy: local
          kubeVolumeSize: 5Gi
          watchToEnd: true
          cacheUnityInstallationOnMac: false
          dockerWorkspacePath: /github/workspace
          skipActivation: false

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
